config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  get '/:page', to: 'places#index'
  resources :places do
    resources :comments, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
  end
  resources :users, only: [:show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email
  
  RATINGS = {
    '1' => '1_star',
    '2' => '2_stars',
    '3' => '3_stars',
    '4' => '4_stars',
    '5' => '5_stars'
  }
  
  def humanize_ratings
    RATINGS.invert[self.rating].to_s.to_i
  end
  
  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  belongs_to :user
  
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos
  geocoded_by :address
  after_validation :geocode
  
  validates :name, presence: true, length: { minimum: 3 }
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       
  has_many :places
  has_many :comments
  
  mount_uploader :profile_image, ProfileImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:profile_image, :remove_profile_image ) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    if @place.valid?
      redirect_to place_path(@place)
    else 
      render :new, status: :unprocessable_entity
    end
  end
  
  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
  
  def destroy
    @place = Place.find(params[:place_id])
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @comment.destroy
    redirect_to place_path(@place)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    if @place.valid?
      redirect_to place_path(@place)
    else 
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy 
    @place = Place.find(params[:place_id])
    @photo = Photo.find(params[:id])
    if @photo.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @photo.destroy
    redirect_to place_path(@place)
  end
  
  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :delete]
  
  def index
    per_page = 10
    puts params[:page]
    @pages_num = Place.all.length / per_page
    @places = Place.paginate(:page => params[:page], :per_page => per_page)
  end
  
  def new
    @place = Place.new
  end
  
  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
    
  end
  
  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end
  
  def edit
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end
  
  def update
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @place = Place.find(params[:id])
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @place.destroy
    redirect_to root_path
  end
  
  private
  
  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user.comments.each do |comment|
      if !comment.place.present?
        comment.destroy
      end
    end
  end
  
  def update 
    @user = User.find(params[:id])
    
    if @user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @user.update_attributes(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def user_params
    params.require(:user).permit(:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
              <i class="fa fa-bars"></i>
          </span>
      </button>
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              <span>New Place</span>
            <% end %>
          </li>
        </ul>
        <ul>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <%  end %>
        </ul>
      </div>
    </nav>
      
    <% if notice.present?  %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="nomster-box col-10 offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary'  %>
  <%  end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="image-container">
        <%= image_tag 'slide1.jpg', class: 'd-block img-fluid' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Find the best pizza places</h3>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="image-container">
      <%= image_tag 'slide2.jpg', class: 'd-block img-fluid' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Looking for hotdogs?</h3>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="navigation_container col-10 offset-1">
  <nav aria-label="Page navigation example">
      <ul class="pagination">
          <% @pages_num.times do |num| %>
          <li class="page-item"><a href="<%= num + 1 %>" class="page-link"><%= num + 1 %></a></li>
          <% end %>
      </ul>
  </nav>
</div>

<% @places.each do |place| %>

  <div class="nomster-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description  %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
      
    <% if place.photos.present? %>
      <div class="col-12 centered place_photo_holder">
        <% photo = place.photos.last %>
        <%= image_tag photo.picture.url, class: "thumbnail" %>
        <br />
        <%= photo.caption  %>
        <br />
        <small><%= photo.user.email %></small>
        <br />
      </div>
    <% end %>
      
    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <% comment = place.comments.last %>
          <% if comment.humanize_ratings.present? %>
            <b>
              <% comment.humanize_ratings.times do |i| %>
                <i class="fa fa-star"></i>
              <% end %>
            </b>
            <b>
              <% (5 - comment.humanize_ratings).times do |i| %>
                <i class="fa fa-star-o"></i>
              <% end %>
            </b>
          <% end %>
          <br />
          <%= comment.message %>
          <small class="float-right"><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>

<% end %>

app/views/places/new.html.erb
<div class="nomster-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary'  %>
  <%  end %>
</div>

app/views/places/show.html.erb
<div class="nomster-box col-10 offset-1">
  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to place_path(@place), method: :delete, data: { confirm:'Are you sure you want to delete this?' }, class: 'btn btn-danger' do %>
        <span>Delete</span>
      <% end %>
    <% end %>
  </div>
    
  <h1><%= @place.name %> </h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>
    
  
  <% if @place.longitude.present? && @place.latitude.present?  %>
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude  %> , lng: <%= @place.longitude  %> };

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GEOCODER_API_KEY'] %>&callback=initMap"></script>

    <div id="map"></div>
  <% end %>
  
  <br />

  <div class="clear"></div>

  <!-- Modal -->
  <div class="modal fade" id="photosModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Add a Photo</h4>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="float: right">
            <span aria-hidden="true" class="fa fa-times"></span>
          </button>
        </div>
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <div class="modal-body">
            <%= f.input :picture, as: :file %>
            <%= f.input :caption %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add Photo", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-10 offset-1">
    <h1 class="float: left;">
      <span>Photos</span>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#photosModal">
          <i class="fa fa-plus-circle"></i>
          <span>Add a Photo</span>
      </button>
    </h1>
  </div>

  <div class="clear"></div>

  <div class="row">
    <% @place.photos.each do |photo| %>
    <div class="col-12 col-sm-6 centered place_photo_holder">
      <%= image_tag photo.picture.url, class: "thumbnail" %>
      <br />
      <%= photo.caption  %>
      <br />
      <small><%= photo.user.email %></small>
      <br />
        
      <% if current_user && photo.user == current_user %>
        <%= link_to place_photo_path(id: photo.id, place_id: @place.id), method: :delete, 
          data: { confirm:'Are you sure you want to delete this photo?' }, class: 'btn btn-danger' do %>
          <span>Delete</span>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="float: right">
            <span aria-hidden="true" class="fa fa-times"></span>
          </button>
        </div>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <div class="modal-body">
            <%= f.input :message %>
            <%= f.input :rating, as: :select, collection: Comment::RATINGS, prompt: "Select One" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-10 offset-1">
    <h1 class="float: left;">
      <span>Comments</span>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
          <i class="fa fa-plus-circle"></i>
          <span>Add a Comment</span>
      </button>
    </h1>
  </div>

  <div class="clear"></div>

  <div class="row">
    <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
          <% if comment.humanize_ratings.present? %>
            <b>
              <% comment.humanize_ratings.times do |i| %>
                <i class="fa fa-star"></i>
              <% end %>
            </b>
            <b>
              <% (5 - comment.humanize_ratings).times do |i| %>
                <i class="fa fa-star-o"></i>
              <% end %>
            </b>
          <% end %>
          <br />
          <%= comment.message %>
          <small class="float-right"><%= comment.user.email %></small>
          <br />
          <% if current_user && comment.user == current_user %>
            <%= link_to place_comment_path(id: comment.id, place_id: @place.id), method: :delete, 
              data: { confirm:'Are you sure you want to delete this comment?' }, class: 'btn btn-danger' do %>
              <span>Delete</span>
            <% end %>
          <% end %>
      </blockquote>
    </div>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div classs="nomster-box">
  <div class="row">
    <div class="col-4 profile_img">
      <% if @user.profile_image.present? %>
        <%= image_tag @user.profile_image.url %>
      <% else %>
        <%= image_tag 'user.png' %>
      <% end %>
      <% if @user === current_user %>
        <br />
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#uploadPhotoModal">
          <i class="fa fa-plus-circle"></i>
          <span>Change Photo</span>
        </button>
        <div class="modal fade" id="uploadPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Change Photo</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="float: right">
                  <span aria-hidden="true" class="fa fa-times"></span>
                </button>
              </div>
              <%= simple_form_for @user, url: user_path(@user) do |f| %>
                <div class="modal-body">
                  <%= f.input :profile_image, as: :file %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.submit "Upload Photo", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-8">
      <h1 style="word-break: break-all;"><%= @user.email %></h1>
      <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4>
        <%= @user.comments.count %> 
        <% if @user.comments.count === 1 %>
          comment
        <% else %>
          comments
        <% end %>
        in total
      </h4>
      <% 1.upto(5) do |i| %>
      <h4>
        <% i.times do |n| %>
          <i class="fa fa-star"></i>
        <% end %>
        <% (5 - i).times do |n| %>
          <i class="fa fa-star-o"></i>
        <% end %>
        <% _rating = i.to_s + '_star' %>
        <% if i > 1 
          _rating = i.to_s + '_stars' 
        end %>
        <% comment_count = @user.comments.where(rating: _rating).count %>
        <%= comment_count %>
        <% if comment_count === 1 %>
          comment
        <% else %>
          comments
        <% end %>
      </h4>
      <% end %>
    </div>
  </div>
  <div class="clear"></div>
</div>

<br /><br />
<h1 class="text-center">My Comments</h1>
<br /><br />
<div class="row">
  <% @user.comments.each do |comment| %>
    <%if comment.place.present? %>
      <div class="col-12 col-sm-6">
        <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
        <blockquote>
          <% if comment.humanize_ratings.present? %>
            <b>
              <% comment.humanize_ratings.times do |i| %>
                <i class="fa fa-star"></i>
              <% end %>
            </b>
            <b>
              <% (5 - comment.humanize_ratings).times do |i| %>
                <i class="fa fa-star-o"></i>
              <% end %>
            </b>
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  <% end %>
</div>

<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />
<div class="row">
  <% @user.places.each do |place| %>
    <div class="booyah-box col-10 offset-1">
      <h1><%= link_to place.name, place_path(place) %></h1>
      <i><%= place.address %></i><br />
      <p><%= place.description %></p><br />

      <% if place.user.present? %>
        <small><%= place.user.email %></small>
      <% end %>

      <% if place.comments.present? %>
        <div class="col-12">
          <blockquote>
            <% if place.comments.last.humanize_ratings.present? %>
              <b><%= place.comments.last.humanize_ratings %></b> -
            <% end %>
            <%= place.comments.last.message %>
            <small><%= place.comments.last.user.email %></small>
          </blockquote>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if @user.places.count === 0 %>
    <div class="booyah-box col-10 offset-1">
      <% current_user === @user ? _user = 'You' : _user = 'This user' %>
      <h4><%= _user  %> have no places.</h4>
      <b>
        <%= link_to new_place_path do %>
          <i class="fa fa-plus-circle"></i>
          <span>Add a New Place</span>
        <% end %>
      </b>
    </div>
  <% end %>
</div>